# Generated by Django 3.1 on 2020-08-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('blogpost_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('heading1', models.CharField(default='', max_length=1000)),
                ('content1', models.CharField(default='', max_length=11111)),
                ('head2', models.CharField(default='', max_length=1111)),
                ('con2', models.CharField(default='', max_length=11111)),
                ('head3', models.CharField(default='', max_length=1111)),
                ('con3', models.CharField(default='', max_length=11111)),
                ('head4', models.CharField(default='', max_length=1111)),
                ('con4', models.CharField(default='', max_length=11111)),
                ('pub_date', models.DateField()),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=80)),
                ('image', models.ImageField(default='', upload_to='blog/images')),
                ('image1', models.ImageField(default='', upload_to='blog/images')),
                ('image2', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
