# Generated by Django 3.1 on 2020-08-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(default=' ', max_length=50)),
                ('phone', models.CharField(default='', max_length=60)),
                ('address', models.CharField(default=' ', max_length=200)),
                ('textarea', models.CharField(max_length=250)),
            ],
        ),
    ]
